// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO4FvWak1QKxAICuLg0NcT9eoHLQtH4As',
    appId: '1:474247250950:web:65351c6229efcf7ad1ef87',
    messagingSenderId: '474247250950',
    projectId: 'kirana-survey',
    authDomain: 'kirana-survey.firebaseapp.com',
    storageBucket: 'kirana-survey.firebasestorage.app',
    measurementId: 'G-LP5TW0RJHX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArpdsda9u45qvHnXytUCG3EL3NHcBbbmo',
    appId: '1:474247250950:android:ed32a7b2ec7f358bd1ef87',
    messagingSenderId: '474247250950',
    projectId: 'kirana-survey',
    storageBucket: 'kirana-survey.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_hvDIR8mH64VEDCNQmVSJgozAS5OZaC0',
    appId: '1:474247250950:ios:ecc0b08af26d4671d1ef87',
    messagingSenderId: '474247250950',
    projectId: 'kirana-survey',
    storageBucket: 'kirana-survey.firebasestorage.app',
    iosBundleId: 'com.lohiya.kiranaSurvey',
  );
}
